sonar.projectKey=ifs24036-pabwe2026-nextjs
sonar.projectName=ifs24036-pabwe2026-nextjs

# Sesuaikan folder sumber kode Anda (biasanya . atau app/ atau src/)
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx

sonar.sourceEncoding=UTF-8

# Path laporan coverage Vitest (sesuaikan jika berbeda)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Folder bawaan Next.js yang harus di-exclude
sonar.exclusions=node_modules/**,(.next|next)/**,coverage/**,public/**,build/**,dist/**,**/*.config.js,**/*.config.ts